###########################################################
# FumetaOS
# App
###########################################################

APP_ID="jellyfin"

APP_NAME="Jellyfin"

APP_TYPE="compose"

APP_IMAGE="jellyfin/jellyfin"
APP_TAG="latest"

APP_COMPOSE="/mnt/datos/Dockersudo/jellyfin/compose.yaml"

APP_DATA="/mnt/datos/Dockersudo/jellyfin"

APP_VERSION="10.11.11"
