#!/bin/bash

###########################################################
# FumetaOS
# App
###########################################################

APP_ID="jellyfin"

###########################################################
# Identidad
###########################################################

APP_NAME="Jellyfin"

APP_DESCRIPTION="Servidor multimedia Jellyfin"

APP_CATEGORY="Media"

APP_ICON="jellyfin"


###########################################################
# Docker
###########################################################

APP_TYPE="compose"

APP_IMAGE="jellyfin/jellyfin"

APP_TAG="latest"

APP_CONTAINER="jellyfin"


###########################################################
# Red
###########################################################

APP_PORT="8097"

APP_URL="http://localhost:8097"

APP_WEBUI="http://[IP]:8097"

APP_HEALTH="http://localhost:8097"

###########################################################
# Datos
###########################################################

APP_COMPOSE="/mnt/datos/Dockersudo/jellyfin/compose.yaml"

APP_DATA="/mnt/datos/Dockersudo/jellyfin"


###########################################################
# Versión
###########################################################

APP_VERSION="10.11.10"


###########################################################
# Autor
###########################################################

APP_AUTHOR="Jellyfin"
