#!/bin/bash

###########################################################

# FumetaOS
# Services Configuration

###########################################################

###########################################################
# Servicios del sistema
###########################################################

SYSTEM_SERVICES="
docker
ssh
tailscaled
casaos
noip-duc
"

###########################################################
# Timers FumetaOS
###########################################################

FUMETAOS_TIMERS="
fumetaos-watch.timer
fumetaos-report.timer
fumetaos-history.timer
fumetaos-history-clean.timer
fumetaos-backup.timer
fumetaos-mac-backup.timer
fumetaos-recovery-backup.timer
fumetaos-recovery-verify.timer
fumetaos-system-upgrade.timer
"
