#!/bin/bash

###########################################################

# FumetaOS
# Services Configuration

###########################################################

SYSTEM_SERVICES="
docker
ssh
tailscaled
casaos
noip-duc
"

FUMETAOS_TIMERS="
fumetaos-watch.timer
fumetaos-report.timer
fumetaos-history.timer
fumetaos-history-clean.timer
fumetaos-backup.timer
fumetaos-timecapsule-mac-backup.timer
fumetaos-recovery-backup.timer
fumetaos-recovery-verify.timer
"
