#!/bin/bash

###########################################################

# FumetaOS

# App

###########################################################

APP_ID="transmission"

###########################################################

# Identidad

###########################################################

APP_NAME="Transmission"

APP_DESCRIPTION="Cliente BitTorrent para descargas automáticas"

APP_CATEGORY="Download"

APP_ICON="transmission"

###########################################################

# Docker

###########################################################

APP_TYPE="compose"

APP_IMAGE="linuxserver/transmission"

APP_TAG="latest"

APP_CONTAINER="transmission"

###########################################################

# Red

###########################################################

APP_PORT="9091"

APP_PORTS="
51413:51413/tcp
51413:51413/udp
"

APP_URL="http://localhost:9091"

APP_WEBUI="http://[IP]:9091"

APP_HEALTH="transmission"

###########################################################

# Datos

###########################################################

APP_COMPOSE="/mnt/datos/Dockersudo/transmission/compose.yaml"

APP_DATA="/mnt/datos/Dockersudo/transmission"

###########################################################

# Versión

###########################################################

APP_VERSION="4.0.6"

###########################################################

# Autor

###########################################################

APP_AUTHOR="LinuxServer.io"
