#!/bin/bash

###########################################################
# FumetaOS
# App
###########################################################

APP_ID="transmission"

###########################################################
# Identidad
###########################################################

APP_NAME="Transmission"

APP_DESCRIPTION="Cliente BitTorrent para descargas automáticas"

APP_CATEGORY="Downloader"

APP_ICON="transmission"


###########################################################
# Docker
###########################################################

APP_TYPE="compose"

APP_IMAGE="linuxserver/transmission"

APP_TAG="4.0.6"

APP_CONTAINER="transmission"


###########################################################
# Red
###########################################################

APP_PORT="9091"

APP_PORTS="
51413:51413/tcp
51413:51413/udp
"

APP_URL="http://localhost:9091"

APP_WEBUI="http://[IP]:9091"


###########################################################
# Datos
###########################################################

APP_COMPOSE="/mnt/datos/Dockersudo/transmission/compose.yaml"

APP_DATA="/mnt/datos/Dockersudo/transmission"


###########################################################
# Entorno
###########################################################

APP_ENV="
PUID=1000
PGID=1000
TZ=Europe/London
USER=$TRANSMISSION_USER
PASS=$TRANSMISSION_PASS
PEERPORT=51413
"


###########################################################
# Volúmenes
###########################################################

APP_VOLUMES="
/DATA/AppData/transmission/config:/config
/DATA/Downloads/incomplete:/downloads/incomplete
/mnt/datos/Multimedia/Torrent:/downloads/complete
/DATA/Downloads/watch:/watch
"


###########################################################
# Versión
###########################################################

APP_VERSION="4.0.6"


###########################################################
# Autor
###########################################################

APP_AUTHOR="Transmission"
