#!/bin/bash

###########################################################
# FumetaOS
# App
###########################################################

APP_ID="pihole"

###########################################################
# Identidad
###########################################################

APP_NAME="Pi-hole"

APP_DESCRIPTION="Bloqueador de anuncios y rastreadores a nivel DNS"

APP_CATEGORY="Networking"

APP_ICON="pihole"

APP_ICON_URL="https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Pi-hole/icon.png"


###########################################################
# Docker
###########################################################

APP_TYPE="compose"

APP_IMAGE="pihole/pihole"

APP_TAG="latest"

APP_CONTAINER="pihole"


###########################################################
# CasaOS
###########################################################

APP_INDEX="/admin/"

APP_PORT_MAP="8080"

APP_WEBUI="http://[IP]:8080/admin/"


###########################################################
# Red
###########################################################

APP_PORT=""

APP_PORTS="
192.168.1.3:53:53/tcp
192.168.1.3:53:53/udp
192.168.1.3:8080:80/tcp
"


###########################################################
# Datos
###########################################################

APP_COMPOSE="/mnt/datos/Dockersudo/pihole/compose.yaml"

APP_DATA="/mnt/datos/Dockersudo/pihole"


###########################################################
# Entorno
###########################################################

APP_ENV="
TZ=Europe/Madrid
FTLCONF_dns_listeningMode=ALL
FTLCONF_dns_upstreams=1.1.1.1;8.8.8.8
"


###########################################################
# Volúmenes
###########################################################

APP_VOLUMES="
/mnt/datos/Dockersudo/pihole/etc-pihole:/etc/pihole
"


###########################################################
# Versión
###########################################################

APP_VERSION="latest"


###########################################################
# Autor
###########################################################

APP_AUTHOR="Pi-hole"
